### ISSUE TITLE
向上偏移的有点大啊

### ISSUE THREAD

**Issue by muyishuangfeng** [llwl1982/FloatOnKeyboardLayout#2]
你好：这个向上偏移的高度有点大啊，虽说可以改变偏移高度，但是，总感觉有点有点怪异。这个原理能否讲解一下？

**Comment by llwl1982** [comment]
原理就是通过ViewTreeObserver.addOnGlobalLayoutListener监听Layout的变化。
偏移大的问题已经修复，使用最新版。最新版可以设置偏移量
